package:
  name: jaclang
  version: 0.7.30
  top-level:
    - jaclang
source:
  url: https://files.pythonhosted.org/packages/6c/c8/d4e0340cc37d5e49170dd5ed40a37d29d6383ff2b9577ca072efbaeb0eb1/jaclang-0.7.30-py3-none-any.whl
  sha256: 8142f40854af7e9c60ed6bca6a7c412c97cb8f7474ef29786f0189360cb49d43
about:
  home: https://jaseci.org
  PyPI: https://pypi.org/project/jaclang
  summary:
    Jac is a unique and powerful programming language that runs on top of Python,
    offering an unprecedented level of intelligence and intuitive understanding.
  license: MIT
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
